services:
  tracker:
    # volumes:
    #   - ./demos:/usr/share/nginx/html/demos:ro
    #   - ./assets:/usr/share/nginx/html/assets:ro
    #   - ./dist:/usr/share/nginx/html/dist:ro
    build: .
    # Useful for local dev so you can edit files without rebuilding image
    # Make sure to run the project's build locally (npm run build) so ./dist exists,
    # or run `docker compose up --build` to build inside the container.
